chat_model_name: qwen3.5-flash
vision_model_name: qwen2.5vl:7b
max_context_token_num: 60000
cache_data_dir: ~/.cache/llm_cache

asset_save_dir: ~/obsidian/attachments
temp_content_dir: ./tmp/parsed_asset

steps: summary,translate,original
src_lang: en
target_lang: zh

extract_pages:
    input_pdf: ~/path/to/input.pdf
    pages:
        - 1-93

gen_conf:
    temperature: 0.7
    top_p: 0.4
    repeat_penalty: 1.2
    num_ctx: 60000

# Placeholders: {src_lang}, {target_lang}, {content}
prompt_translate: |
    你是一个翻译助手，请将下面的{src_lang}内容翻译成{target_lang}。

    下面是需要翻译的内容：

    {content}
    ----

    注意：
    - 如果要翻译的内容为引用文献、算法伪代码、代码、人名，则不需要翻译，直接返回原文
    - 你只需要输出最终翻译结果，不要输出逐步思考过程。

    现在开始逐步思考

prompt_summary: |
    你是一个阅读助手，阅读下面的{src_lang}内容，并完成指令。

    下面是文档内容

    {content}
    ----

    指令：使用{target_lang}语言，总结{src_lang}内容。
    - 如果是学术论文，请总结论文的主要贡献、方法、实验和结论。
    - 如果是技术文档，请总结技术的核心概念、功能和应用场景。
    - 如果是一般性文档（书籍，文章等），请总结文档的主要内容和关键点。

    注意：
    - 忽略引用部分内容，只总结文档正文部分。
    - 你只需要输出最终总结结果，不要输出逐步思考过程。

    现在开始逐步思考